<a href="https://colab.research.google.com/github/Jennapa-colab/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 
#การรับทำงานกับ ข้อมูลที่เป็นตัวเลข (อยู่ในรูปแบบ Matrix)

##Numpy Array


##สร้าง numpy array

In [2]:
np_a = np.array([[1,2,3],[4,5,6]]) 
# สร้าง numpy array ที่มี 2 เเถว 3 หลัก สร้าง matrix จาก list

In [3]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np_a.shape 
# เช็คขนาด (เเถว,หลัก)

(2, 3)

In [5]:
np_b = np.array([[1,4],[2,5],[3,6]])
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

##matrix transpose

In [6]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

##สร้าง matrix เริ่มต้น (zeros,ones)

In [7]:
np_z = np.zeros((4,5))   # matrix เริ่มต้นคือ matrix ที่กำหนดค่าให้เป็น 0,1
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [9]:
np_200 = 200 * np.ones((4,7))
np_200 # ทำเป็นค่า 200 ทุกค่าใน matrix เอา 200 

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

##สร้าง matrix random ค่าเเบบมั่ว

In [10]:
np.random.randn(5,5) 
#random เลขมาจาก normal distribution ที่มี mu=0 std=1

array([[-0.44077059, -0.93176574,  0.62381884,  1.07577813,  1.1398445 ],
       [-1.84059715, -1.78025673, -0.1500812 ,  0.88633724, -0.09619098],
       [-0.59228116, -0.62624805,  1.44032128, -0.60880752, -0.13972164],
       [ 0.76452881, -1.31668047,  0.36325298, -2.17997219,  0.91177794],
       [-0.20794163, -1.85948885, -2.04010626,  0.59565313,  0.69831853]])

In [11]:
2+(5*np.random.randn(3,3)) 
#normal distribution ที่มี mu=2 std=5

array([[ 6.06481276,  4.66391442,  7.28100529],
       [ 7.83601067, -2.24974088,  2.20192881],
       [-0.21947111, 10.87270878,  5.07951487]])

In [12]:
np.random.randint(5,11,(4,5)) 
#ค่าตั้งเเต่ระหว่าง 5 ถึง 10 (5,11,(ขนาด 4x5))

array([[10,  8, 10,  6,  8],
       [ 9,  7,  6,  9, 10],
       [ 8,  5,  6, 10,  5],
       [ 7,  5,  5, 10,  6]])

##matrix properties

In [14]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np_a.T  #transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [16]:
1 + np_a  #adding scalar to matrix

array([[2, 3, 4],
       [5, 6, 7]])

In [17]:
2 * np_a  #multipling scalar to matrix

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [18]:
np_c = np.array([[6,5,4],[3,2,1]])
np_c

array([[6, 5, 4],
       [3, 2, 1]])

In [19]:
np_a + np_c  #adding matrix to matrix

array([[7, 7, 7],
       [7, 7, 7]])

In [20]:
np_a.shape

(2, 3)

In [21]:
np_c.shape

(2, 3)

In [22]:
np_c.T.shape

(3, 2)

In [23]:
np.dot(np_a,np_c.T)  #multipling matrix to matrix   (a,b) x (b,c) = (a,c)

array([[28, 10],
       [73, 28]])

##Indexing & Slicing

In [24]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
np_a[1,1]

5

In [26]:
np_a[:2,:2]

array([[1, 2],
       [4, 5]])

In [27]:
np_a[0,:]

array([1, 2, 3])

##Useful functions

In [32]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
np.sum(np_a)

21

In [34]:
np.sum(np_a,axis=0)  # axis 0 ก็คือรวมเลขในแต่ละแถว

array([5, 7, 9])

In [35]:
np.sum(np_a,axis=1)  # axis 1 ก็คือรวมเลขในแต่ละหลัก

array([ 6, 15])

In [36]:
np.mean(np_a)

3.5

In [37]:
np.mean(np_a,axis=0)  #หา mean ของ column

array([2.5, 3.5, 4.5])

##วนลูปเอง
##summation


In [38]:
np_a.shape

(2, 3)

In [39]:
sum_all = 0

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all = sum_all + np_a[row,col]
        print(f'we are at row={row},col={col} np_a[{row},{col}]={np_a[row,col]}  sum_all={sum_all}')
print(sum_all)

we are at row=0,col=0 np_a[0,0]=1  sum_all=1
we are at row=0,col=1 np_a[0,1]=2  sum_all=3
we are at row=0,col=2 np_a[0,2]=3  sum_all=6
we are at row=1,col=0 np_a[1,0]=4  sum_all=10
we are at row=1,col=1 np_a[1,1]=5  sum_all=15
we are at row=1,col=2 np_a[1,2]=6  sum_all=21
21


In [40]:
sum_all = np.zeros(np_a.shape[1])

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all[col] = sum_all[col] + np_a[row,col]
print(sum_all)

[5. 7. 9.]


##Quiz กลุ่ม

##วนลูปหาค่า

np.sum(np_a,axis=1)

np.mean(np_a)

np.mean(np_a,axis=0)

np.mean(np_a,axis=1)