<a href="https://colab.research.google.com/github/Jennapa-colab/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np 
#การรับทำงานกับ ข้อมูลที่เป็นตัวเลข (อยู่ในรูปแบบ Matrix)

##Numpy Array


##สร้าง numpy array

In [4]:
np_a = np.array([[1,2,3],[4,5,6]]) 
# สร้าง numpy array ที่มี 2 เเถว 3 หลัก สร้าง matrix จาก list

In [5]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np_a.shape 
# เช็คขนาด (เเถว,หลัก)

(2, 3)

In [7]:
np_b = np.array([[1,4],[2,5],[3,6]])
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

##matrix transpose

In [8]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

##สร้าง matrix เริ่มต้น (zeros,ones)

In [9]:
np_z = np.zeros((4,5))   # matrix เริ่มต้นคือ matrix ที่กำหนดค่าให้เป็น 0,1
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [11]:
np_200 = 200 * np.ones((4,7))
np_200 # ทำเป็นค่า 200 ทุกค่าใน matrix เอา 200 

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

##สร้าง matrix random ค่าเเบบมั่ว

In [13]:
np.random.randn(5,5) 
#random เลขมาจาก normal distribution ที่มี mu=0 std=1

array([[-0.33718701, -1.85209681, -1.82020196,  1.22934808,  1.80877172],
       [ 2.02777216, -2.26253876, -0.93106903,  0.46696922,  0.32030959],
       [-0.83287904,  0.2687306 , -0.3827038 , -1.31985865,  0.37256239],
       [ 0.59623443, -0.915384  ,  0.14455398,  0.41924319,  0.18242958],
       [-0.73922725, -1.01008059,  0.47191637, -0.47682149, -0.85830476]])

In [14]:
2+(5*np.random.randn(3,3)) 
#normal distribution ที่มี mu=2 std=5

array([[-5.12618702,  3.17470862,  6.33345313],
       [ 7.65809926,  1.40528549,  3.34404922],
       [ 7.94166614, -3.03048289, -3.27631162]])

In [15]:
np.random.randint(5,11,(4,5)) 
#ค่าตั้งเเต่ระหว่าง 5 ถึง 10 (5,11,(ขนาด 4x5))

array([[ 6,  8, 10,  7,  6],
       [ 6, 10,  7,  8, 10],
       [ 8,  5,  5,  7, 10],
       [ 6,  8,  9,  9, 10]])