<a href="https://colab.research.google.com/github/Jennapa-colab/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np 
#การรับทำงานกับ ข้อมูลที่เป็นตัวเลข (อยู่ในรูปแบบ Matrix)

##Numpy Array


##สร้าง numpy array

In [3]:
np_a = np.array([[1,2,3],[4,5,6]]) 
# สร้าง numpy array ที่มี 2 เเถว 3 หลัก สร้าง matrix จาก list

In [4]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np_a.shape 
# เช็คขนาด (เเถว,หลัก)

(2, 3)

In [6]:
np_b = np.array([[1,4],[2,5],[3,6]])
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

##matrix transpose

In [7]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

##สร้าง matrix เริ่มต้น (zeros,ones)

In [8]:
np_z = np.zeros((4,5))   # matrix เริ่มต้นคือ matrix ที่กำหนดค่าให้เป็น 0,1
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [10]:
np_200 = 200 * np.ones((4,7))
np_200 # ทำเป็นค่า 200 ทุกค่าใน matrix เอา 200 

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

##สร้าง matrix random ค่าเเบบมั่ว

In [11]:
np.random.randn(5,5) 
#random เลขมาจาก normal distribution ที่มี mu=0 std=1

array([[ 0.28127673, -0.51097914, -0.51711182, -1.06675546,  1.64456611],
       [ 0.47455505, -0.28419625,  0.92233956, -0.15188141,  0.86897827],
       [ 1.05371804, -0.01294527,  0.43496842, -0.32313423,  0.54479798],
       [ 1.66419586,  0.48901496, -1.4223533 ,  0.64730094, -1.36597605],
       [-1.59733518,  0.49274417,  0.04787593,  1.39769174,  0.56367679]])

In [12]:
2+(5*np.random.randn(3,3)) 
#normal distribution ที่มี mu=2 std=5

array([[-7.41528502,  0.88388384, -4.81167603],
       [ 2.45622104,  3.359931  , -2.62462369],
       [ 8.20737606, -5.78513799, -3.17396467]])

In [13]:
np.random.randint(5,11,(4,5)) 
#ค่าตั้งเเต่ระหว่าง 5 ถึง 10 (5,11,(ขนาด 4x5))

array([[10,  7,  7, 10,  5],
       [ 9,  9,  6,  8,  9],
       [ 7,  8,  7,  8,  6],
       [ 9,  8,  6, 10,  8]])

##matrix properties

In [14]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np_a.T  #transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [16]:
1 + np_a  #adding scalar to matrix

array([[2, 3, 4],
       [5, 6, 7]])

In [17]:
2 * np_a  #multipling scalar to matrix

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [18]:
np_c = np.array([[6,5,4],[3,2,1]])
np_c

array([[6, 5, 4],
       [3, 2, 1]])

In [19]:
np_a + np_c  #adding matrix to matrix

array([[7, 7, 7],
       [7, 7, 7]])

In [20]:
np_a.shape

(2, 3)

In [21]:
np_c.shape

(2, 3)

In [22]:
np_c.T.shape

(3, 2)

In [23]:
np.dot(np_a,np_c.T)  #multipling matrix to matrix   (a,b) x (b,c) = (a,c)

array([[28, 10],
       [73, 28]])

##Indexing & Slicing

In [24]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
np_a[1,1]

5

In [26]:
np_a[:2,:2]

array([[1, 2],
       [4, 5]])

In [27]:
np_a[0,:]

array([1, 2, 3])

##Useful functions

In [28]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
np.sum(np_a)

21

In [30]:
np.sum(np_a,axis=0)  # axis 0 ก็คือรวมเลขในแต่ละแถว

array([5, 7, 9])

In [31]:
np.sum(np_a,axis=1)  # axis 1 ก็คือรวมเลขในแต่ละหลัก

array([ 6, 15])

In [32]:
np.mean(np_a)

3.5

In [33]:
np.mean(np_a,axis=0)  #หา mean ของ column

array([2.5, 3.5, 4.5])

##วนลูปเอง
##summation


In [34]:
np_a.shape

(2, 3)

In [35]:
sum_all = 0

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all = sum_all + np_a[row,col]
        print(f'we are at row={row},col={col} np_a[{row},{col}]={np_a[row,col]}  sum_all={sum_all}')
print(sum_all)

we are at row=0,col=0 np_a[0,0]=1  sum_all=1
we are at row=0,col=1 np_a[0,1]=2  sum_all=3
we are at row=0,col=2 np_a[0,2]=3  sum_all=6
we are at row=1,col=0 np_a[1,0]=4  sum_all=10
we are at row=1,col=1 np_a[1,1]=5  sum_all=15
we are at row=1,col=2 np_a[1,2]=6  sum_all=21
21


In [36]:
sum_all = np.zeros(np_a.shape[1])

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all[col] = sum_all[col] + np_a[row,col]
print(sum_all)

[5. 7. 9.]


##Quiz กลุ่ม

วนลูปหาค่า

1. np.sum(np_a,axis=1)

2. np.mean(np_a)

3. np.mean(np_a,axis=0)

4. np.mean(np_a,axis=1)

5. np.max(np_a)

6. np.max(np_a,axis=0)

7. np.max(np_a,axis=1)

8. np.min(np_a)

9. np.min(np_a,axis=0)

10. np.min(np_a,axis=1)


In [37]:
sum_all = np.zeros(np_a.shape[0])

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all[row] = sum_all[row] + np_a[row,col]     
print(sum_all)

[ 6. 15.]


In [38]:
mean_all = 0
for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        mean_all = mean_all + np_a[row,col]
mean_all = mean_all/(np_a.shape[0]*np_a.shape[1])
print(mean_all)

3.5


In [39]:
mean_all = np.zeros(np_a.shape[1])

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        mean_all[col] = mean_all[col] + np_a[row,col]/np_a.shape[0]
print(mean_all)

[2.5 3.5 4.5]


In [40]:
sum_all = np.zeros(np_a.shape[0])

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all[row] = sum_all[row] + np_a[row,col]
sum_all = sum_all/np_a.shape[1]
print(sum_all)

[2. 5.]


In [41]:

max_a = -100000000
for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        if np_a[row,col] > max_a :
            max_a = np_a[row,col]
print(max_a)

6


In [42]:
max_all = -100000 * np.ones(np_a.shape[1])
for col in range(np_a.shape[1]):
    for row in range(np_a.shape[0]):
        if np_a[row,col] > max_all[col]: 
            max_all[col] = np_a[row,col]
print(max_all)

[4. 5. 6.]


In [43]:
max_all = np.zeros(np_a.shape[0])
for row in range(np_a.shape[0]):
    max_all[row] = max(np_a[row,:])
print(max_all)

[3. 6.]


In [44]:
minV = 100000
for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        if np_a[row,col] < minV:
            minV = np_a[row,col]
print(minV)

1


In [47]:
min_all = np.zeros(np_a.shape[1])

for col in range(np_a.shape[1]):
    min_all[col] = min(np_a[:,col])
print(min_all)

[1. 2. 3.]


In [48]:
min_row = np.zeros(np_a.shape[0])
for row in range(np_a.shape[0]):
   min_row[row] = min(np_a[row,:])
print(min_row)

[1. 4.]
